name: Code Quality Checks

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run checks on'
        required: true

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 mypy bandit

    - name: Run Pylint
      run: | 
          pylint polars_extensions
          flake8 polars_extensions
          mypy polars_extensions
          bandit -r polars_extensions
          
    - name: Run Flake8
      run: flake8 polars_extensions

    - name: Run MyPy
      run: mypy polars_extensions

    - name: Run Bandit
      run: bandit -r polars_extensions
